routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/register', 'register.index')->name('register.index');
Route::post('/register/store', [RegisterController::class, 'store'])->name('register.store');

Route::get('/', [\App\Http\Controllers\MainController::class, 'index'])->name('main.index');
Route::view('register', 'register.index')->name('register.index');
Route::view('/login', 'login.index')->name('login.index');
Route::get('/logout', LogoutController::class)->name('logout');
Route::post('/login/store', [LoginController::class, 'store'])->name('login.store');

Route::patch('/profile/update/{id}', [ProfileController::class, 'update'])->name('profile.update');

Route::get('/profile/{id}', [ProfileController::class, 'index'])->name('profile.index');

Route::prefix('katalog')
    ->name('catalog.')
    ->controller(\App\Http\Controllers\CatalogController::class)
    ->group(function () {
        Route::get('/', 'index')->name('catalog');
        Route::get('/show/{id}', 'show')->name('show');
    });

Route::prefix('kontakts')
    ->name('kontakts.')
    ->controller(\App\Http\Controllers\ContactController::class)
    ->group(function () {
        Route::get('/', 'index')->name('kontakt');
        Route::post('/store', 'store')->name('store');
    });

Route::prefix('korzina')
    ->name('korzina.')
    ->group( function () {
    Route::get('/', [\App\Http\Controllers\BusketController::class, 'index'])->name('korzina');
    Route::post('/add-order', [\App\Http\Controllers\BusketController::class, 'addOrder'])->name('order');
    Route::post('/delete', [\App\Http\Controllers\BusketController::class, 'delete'])->name('delete');
    Route::post('/buy', [\App\Http\Controllers\BusketController::class, 'buyOrder'])->name('buy');
    Route::post('/buy-ball', [\App\Http\Controllers\BusketController::class, 'buyBall'])->name('buy-ball');
});
Route::view('/kab', 'kab.kab')->name('kab.kab');

Route::prefix('kab')
    ->name('kab.')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\KabController::class, 'index'])->name('kab');
        Route::post('/review', [\App\Http\Controllers\KabController::class, 'review'])->name('review');
        Route::delete('/delete/{id}', [\App\Http\Controllers\KabController::class, 'deleteAdress'])->name('delete');
        Route::post('/create', [\App\Http\Controllers\KabController::class, 'addAddress'])->name('create');
    });

Route::prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('index');

        Route::prefix('artist')
            ->name('artist.')
            ->controller(\App\Http\Controllers\Admin\ArtistController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('genre')
            ->name('genre.')
            ->controller(\App\Http\Controllers\Admin\GenreController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('album')
            ->name('album.')
            ->controller(\App\Http\Controllers\Admin\AlbumController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('contact')
            ->name('contact.')
            ->controller(\App\Http\Controllers\Admin\ContactController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::patch('/update', 'update')->name('update');
            });

        Route::prefix('user')
            ->name('user.')
            ->controller(\App\Http\Controllers\Admin\UserController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::post('/block/{id}', 'block')->name('block');
                Route::delete('/destroy', 'delete')->name('destroy');
            });

        Route::prefix('feedback')
            ->name('feedback.')
            ->controller(\App\Http\Controllers\Admin\FeedbackController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('delete');
                Route::post('answer/{id}', 'answer')->name('answer');
            });

        Route::prefix('record')
            ->name('record.')
            ->controller(\App\Http\Controllers\Admin\RecordController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('record-music')
            ->name('record-music.')
            ->controller(\App\Http\Controllers\Admin\RecordMusicController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::post('/store', 'store')->name('store');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('destroy');
            });

        Route::prefix('review')
            ->name('review.')
            ->controller(\App\Http\Controllers\Admin\ReviewController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::delete('/delete/{id}', 'delete')->name('delete');
            });

        Route::prefix('order')
            ->name('order.')
            ->controller(\App\Http\Controllers\Admin\OrderController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::patch('/update/{id}', 'update')->name('update');
            });

    });

Route::post('/kab/add', [\App\Http\Controllers\KabController::class, 'addAddress'])->name('kab.add');

app/Models/Genre.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Genre extends Model
{
    use Sluggable;

    /**
     * @var string[]
     */
    protected $fillable = [
        'title',
        'slug'
    ];

    /**
     * @return array[]
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    /**
     * @return HasMany
     */
    public function records(): HasMany
    {
        return $this->hasMany(Record::class);
    }
}

app/Http/Controllers/Admin/GenreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Genre\StoreRequest;
use App\Http\Requests\Genre\UpdateRequest;
use App\Models\Genre;
use Illuminate\Http\Request;

class GenreController extends Controller
{
    public function index ()
    {
        return view('admin.genre.index', [
            'genres' => Genre::all()
        ]);
    }

    public function create ()
    {
        return view('admin.genre.create');
    }

    public function store (StoreRequest $request)
    {
        Genre::query()->create([
            'title' => $request->title,
            'slug' => $request->slug
        ]);

        return redirect()->route('admin.genre.index')->with('success', 'Жанр успешно добавлен');
    }

    public function edit (Genre $id)
    {
        return view('admin.genre.edit', [
            'genre' => $id
        ]);
    }

    public function update (Genre $id, UpdateRequest $request)
    {
        $id->update([
            'title' => $request->title,
            'slug' => $request->slug
        ]);

        return redirect()->route('admin.genre.index')->with('success', 'Жанр успешно обновлен');
    }

    public function delete (Genre $id)
    {
        $id->delete();

        return redirect()->route('admin.genre.index')->with('success', 'Жанр успешно удален');
    }
}

resources/views/admin/genre/create.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header pb-0">
                        <h4>Создание  жанра</h4>
                    </div>
                    <form method="post" action="{{route('admin.genre.store')}}" enctype="multipart/form-data" class="form theme-form">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <div class="mb-3">
                                        <label class="form-label" for="exampleFormControlInput1"> Название</label>
                                        <input class="form-control" id="exampleFormControlInput1" name="title" type="text" placeholder="Тимати">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="mb-3">
                                        <label class="form-label" for="exampleFormControlInput1">Слаг</label>
                                        <input class="form-control" id="exampleFormControlInput1" name="slug" type="text" placeholder="Rock">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-end">
                            <button class="btn btn-primary" type="submit">Добавить  жанр</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/genre/edit.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header pb-0">
                            <h4>Редактирование жанра</h4>
                        </div>
                        <form method="post" action="{{route('admin.genre.update', ['id' => $genre->id])}}" enctype="multipart/form-data" class="form theme-form">
                            @method('PATCH')
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="exampleFormControlInput1"> Название</label>
                                            <input class="form-control" id="exampleFormControlInput1" name="title" value="{{$genre->title}}" type="text" placeholder="Тимати">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="exampleFormControlInput1">Слаг</label>
                                            <input class="form-control" id="exampleFormControlInput1" value="{{$genre->slug}}" name="slug" type="text" placeholder="Rock">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-end">
                                <button class="btn btn-primary" type="submit">Редактировать жанр</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/genre/index.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h3> Жанры</h3>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}"><i data-feather="home"></i></a></li>
                            <li class="breadcrumb-item">Жанры</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid basic_table">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Список  жанров</h4>
                            <br>
                            <a href="{{route('admin.genre.create')}}" class="btn btn-primary">Добавить жанр</a>
                        </div>
                        <div class="table-responsive theme-scrollbar">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Название</th>
                                    <th scope="col">Слаг</th>
                                    <th scope="col">Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($genres as $genre)
                                    <tr>
                                        <th scope="row">{{$genre->id}}</th>
                                        <td class="">{{$genre->title}}</td>
                                        <td class="">{{$genre->slug}}</td>
                                        <td>
                                            <div class="row">
                                                <a href="{{route('admin.genre.edit', ['id' => $genre->id])}}">Редактировать</a>
                                                <form action="{{route('admin.genre.destroy', ['id' => $genre->id])}}" method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-primary">Удалить</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection