routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/register', 'register.index')->name('register.index');
Route::post('/register/store', [RegisterController::class, 'store'])->name('register.store');

Route::get('/', [\App\Http\Controllers\MainController::class, 'index'])->name('main.index');
Route::view('register', 'register.index')->name('register.index');
Route::view('/login', 'login.index')->name('login.index');
Route::get('/logout', LogoutController::class)->name('logout');
Route::post('/login/store', [LoginController::class, 'store'])->name('login.store');

Route::patch('/profile/update/{id}', [ProfileController::class, 'update'])->name('profile.update');

Route::get('/profile/{id}', [ProfileController::class, 'index'])->name('profile.index');

Route::prefix('katalog')
    ->name('catalog.')
    ->controller(\App\Http\Controllers\CatalogController::class)
    ->group(function () {
        Route::get('/', 'index')->name('catalog');
        Route::get('/show/{id}', 'show')->name('show');
    });

Route::prefix('kontakts')
    ->name('kontakts.')
    ->controller(\App\Http\Controllers\ContactController::class)
    ->group(function () {
        Route::get('/', 'index')->name('kontakt');
        Route::post('/store', 'store')->name('store');
    });

Route::prefix('korzina')
    ->name('korzina.')
    ->group( function () {
    Route::get('/', [\App\Http\Controllers\BusketController::class, 'index'])->name('korzina');
    Route::post('/add-order', [\App\Http\Controllers\BusketController::class, 'addOrder'])->name('order');
    Route::post('/delete', [\App\Http\Controllers\BusketController::class, 'delete'])->name('delete');
    Route::post('/buy', [\App\Http\Controllers\BusketController::class, 'buyOrder'])->name('buy');
    Route::post('/buy-ball', [\App\Http\Controllers\BusketController::class, 'buyBall'])->name('buy-ball');
});
Route::view('/kab', 'kab.kab')->name('kab.kab');

Route::prefix('kab')
    ->name('kab.')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\KabController::class, 'index'])->name('kab');
        Route::post('/review', [\App\Http\Controllers\KabController::class, 'review'])->name('review');
        Route::delete('/delete/{id}', [\App\Http\Controllers\KabController::class, 'deleteAdress'])->name('delete');
        Route::post('/create', [\App\Http\Controllers\KabController::class, 'addAddress'])->name('create');
    });

Route::prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('index');

        Route::prefix('artist')
            ->name('artist.')
            ->controller(\App\Http\Controllers\Admin\ArtistController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('genre')
            ->name('genre.')
            ->controller(\App\Http\Controllers\Admin\GenreController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('album')
            ->name('album.')
            ->controller(\App\Http\Controllers\Admin\AlbumController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('contact')
            ->name('contact.')
            ->controller(\App\Http\Controllers\Admin\ContactController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::patch('/update', 'update')->name('update');
            });

        Route::prefix('user')
            ->name('user.')
            ->controller(\App\Http\Controllers\Admin\UserController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::post('/block/{id}', 'block')->name('block');
                Route::delete('/destroy', 'delete')->name('destroy');
            });

        Route::prefix('feedback')
            ->name('feedback.')
            ->controller(\App\Http\Controllers\Admin\FeedbackController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('delete');
                Route::post('answer/{id}', 'answer')->name('answer');
            });

        Route::prefix('record')
            ->name('record.')
            ->controller(\App\Http\Controllers\Admin\RecordController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::post('/store', 'store')->name('store');
                Route::patch('/update/{id}', 'update')->name('update');
                Route::delete('/destroy/{id}', 'delete')->name('destroy');
            });

        Route::prefix('record-music')
            ->name('record-music.')
            ->controller(\App\Http\Controllers\Admin\RecordMusicController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/create', 'create')->name('create');
                Route::post('/store', 'store')->name('store');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::delete('/delete/{id}', 'delete')->name('destroy');
            });

        Route::prefix('review')
            ->name('review.')
            ->controller(\App\Http\Controllers\Admin\ReviewController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::delete('/delete/{id}', 'delete')->name('delete');
            });

        Route::prefix('order')
            ->name('order.')
            ->controller(\App\Http\Controllers\Admin\OrderController::class)
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::get('/edit/{id}', 'edit')->name('edit');
                Route::patch('/update/{id}', 'update')->name('update');
            });

    });

Route::post('/kab/add', [\App\Http\Controllers\KabController::class, 'addAddress'])->name('kab.add');

app/Models/User.php
<?php

namespace App\Models;

use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasAvatar;
use Filament\Panel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements FilamentUser, HasAvatar
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar_url',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function getFilamentAvatarUrl(): ?string
    {
        return $this->avatar_url ? Storage::url($this->avatar_url) : null;
    }

    public function canAccessPanel(Panel $panel): bool
    {
        return str_ends_with($this->email, 'admin@admin.com');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\RoleEnum;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class UserController extends Controller
{
    public function index ()
    {
        return view('admin.user.index', [
            'users' => User::query()->where('role_id', '=', RoleEnum::USER->value)->get()
        ]);
    }


    public function block (int $id)
    {
        $email = User::query()->find($id)->email;
        Cache::add('user-block-' . $email, $email, now()->addHours(24));

        return redirect()->route('admin.user.index');
    }

    public function delete (int $id)
    {
        User::query()->find($id)->delete();

        return redirect()->route('admin.user.index');
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.admin.main')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Пользователи</h3>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.index')}}"><i data-feather="home"></i>Главная</a></li>
                            <li class="breadcrumb-item">Пользователи</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid basic_table">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Список Пользователей</h4>
                        </div>
                        <div class="table-responsive theme-scrollbar">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Имя</th>
                                    <th scope="col">Почта</th>
                                    <th scope="col">Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <th scope="row">{{$user->id}}</th>
                                        <td class="">{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>
                                            <div class="row">
                                                <form action="{{route('admin.user.block', ['id' => $user->id])}}"
                                                      method="post">
                                                    @csrf
                                                    <button type="submit" class="btn btn-primary">Заблокировать на 24 часа
                                                    </button>
                                                </form>
                                                <form action="{{route('admin.user.destroy', ['id' => $user->id])}}"
                                                      method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-primary">Удалить</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection